# Generated by Django 6.0.2 on 2026-02-18 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('exchange', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='Narrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('news', 'News'), ('reddit', 'Reddit'), ('twitter', 'Twitter/X'), ('other', 'Other')], max_length=20)),
                ('source_name', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narratives', to='api.stock')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='HypeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('extreme', 'Extreme')], default='low', max_length=10)),
                ('sentiment_imbalance', models.FloatField(default=0.0)),
                ('social_news_ratio', models.FloatField(default=0.0)),
                ('velocity_factor', models.FloatField(default=0.0)),
                ('explanation', models.TextField(blank=True, default='')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hype_scores', to='api.stock')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='VelocityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_count', models.IntegerField(default=0)),
                ('velocity_score', models.FloatField(default=0.0)),
                ('acceleration', models.FloatField(default=0.0)),
                ('trend', models.CharField(choices=[('accelerating', 'Accelerating'), ('decelerating', 'Decelerating'), ('stable', 'Stable')], default='stable', max_length=15)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='velocity_metrics', to='api.stock')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], max_length=10)),
                ('positive_score', models.FloatField(default=0.0)),
                ('negative_score', models.FloatField(default=0.0)),
                ('neutral_score', models.FloatField(default=0.0)),
                ('compound_score', models.FloatField(default=0.0)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('narrative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='api.narrative')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_scores', to='api.stock')),
            ],
            options={
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['stock', '-analyzed_at'], name='api_sentime_stock_i_9c5b43_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='narrative',
            index=models.Index(fields=['stock', '-published_at'], name='api_narrati_stock_i_a1061d_idx'),
        ),
        migrations.AddIndex(
            model_name='hypescore',
            index=models.Index(fields=['stock', '-computed_at'], name='api_hypesco_stock_i_b5e5c0_idx'),
        ),
        migrations.AddIndex(
            model_name='velocitymetric',
            index=models.Index(fields=['stock', '-computed_at'], name='api_velocit_stock_i_132f35_idx'),
        ),
    ]
