# Generated by Django 6.0.2 on 2026-02-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narrative',
            name='source',
            field=models.CharField(choices=[('news', 'News'), ('rss', 'RSS Feed'), ('reddit', 'Reddit'), ('twitter', 'Twitter/X'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='narrative',
            constraint=models.UniqueConstraint(condition=models.Q(('url', ''), _negated=True), fields=('url',), name='unique_narrative_url'),
        ),
    ]
