# Generated by Django 6.0.2 on 2026-02-18 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_narrative_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_publish', models.FloatField(blank=True, null=True)),
                ('price_1h', models.FloatField(blank=True, null=True)),
                ('price_4h', models.FloatField(blank=True, null=True)),
                ('price_24h', models.FloatField(blank=True, null=True)),
                ('impact_1h', models.FloatField(blank=True, null=True)),
                ('impact_4h', models.FloatField(blank=True, null=True)),
                ('impact_24h', models.FloatField(blank=True, null=True)),
                ('direction_24h', models.CharField(blank=True, choices=[('up', 'Up'), ('down', 'Down'), ('flat', 'Flat')], default='', max_length=5)),
                ('price_fetched_at_publish', models.BooleanField(default=False)),
                ('price_fetched_1h', models.BooleanField(default=False)),
                ('price_fetched_4h', models.BooleanField(default=False)),
                ('price_fetched_24h', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('narrative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_impact', to='api.narrative')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_impacts', to='api.stock')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock', '-created_at'], name='api_priceim_stock_i_4d7f87_idx'), models.Index(fields=['direction_24h'], name='api_priceim_directi_386452_idx')],
            },
        ),
    ]
