# Generated by Django 6.0.2 on 2026-02-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='service',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('groq', 'Groq'), ('twelvedata', 'Twelve Data'), ('gnews', 'GNews'), ('reddit_id', 'Reddit Client ID'), ('reddit_secret', 'Reddit Client Secret')], max_length=20),
        ),
    ]
